#!/bin/sh
#
# Perform necessary osv-scanner setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Thank you for installing osv-scanner!"

exit 0
